apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-1
  labels:
    app: web-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-1
  template:
    metadata:
      labels:
        app: web-1
    spec:
      containers:
        - name: webserver
          image: us-central1-docker.pkg.dev/cloudside-academy/harsh-test-repo/jenkins-argo:v0
