apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yml
- svc.yml
namespace: default
images:
- name: us-central1-docker.pkg.dev/cloudside-academy/harsh-test-repo/test-image
  newTag: v2
